### ISSUE TITLE
Cannot compile with cordova@7 for iOS

### ISSUE THREAD

**Issue by TianleZhang** [newrelic/newrelic-cordova-plugin#2]
Building iOS build with cordova@7 failed, it says. 

<NewRelicAgent.framework/NerRelic.h> not found. And checked, the framework is empty somehow. But it does work with cordova@6.5.0

**Comment by arielgelbard** [comment]
same thing here to!

```
In file included from /Users/.../Plugins/newrelic-cordova-plugin/NewRelicCordovaPlugin.m:10:
/Plugins/newrelic-cordova-plugin/NewRelicCordovaPlugin.h:12:9: fatal error: 'NewRelicAgent/NewRelic.h' file not found
#import <NewRelicAgent/NewRelic.h>
```

**Comment by bryce-newrelic** [comment]
This should be fixed now.
